version: "3.9"
services:
  node:
    image: node:14
    working_dir: /home
    volumes:
      - ./:/home
    ports:
      - "8000:8000"
    tty: true
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        yarn
        yarn start
